### ISSUE TITLE
Invalid repo-meta

### ISSUE THREAD

**Issue by brettbotty** [brett-test/test-repo#1]
In trying to federate this rpeo with the CMDB, [repo_meta_to_cmdb](https://github.com/byu-oit/repo_meta_to_cmdb) validated the contents ofthe [repo-meta file](https://github.com/byu-oit/repo-meta) with[repo_meta_validation_service](https://github.com/byu-oit/repo_meta_validation_service) and discoveredthe following issues:
**error** (Federation will work, but corresponding fields may be missing)
- [ ] standard_change_template_id is an invalid type, expected: str; actual: int
- [ ] Database "library:production" not found ([allowed values](https://it.byu.edu/nav_to.do?uri=%2Fcmdb_ci_database_list.do%3Fsysparm_query%3D))
- [ ] Software "crazy-friday-videos" not found ([allowed values](https://it.byu.edu/nav_to.do?uri=%2Fcmdb_ci_application_software_list.do%3Fsysparm_query%3D))

**info**
- [ ] standard_change_template_id was renamed to standard_change_template in version 2.1
